export {default as About} from './About'
export {default as Header} from './Header'
export {default as Hero} from './Hero'
export {default as Portfolio} from './Portfolio'
export {default as Skill} from './Skill'
export {default as Contact} from './Contact'